---
creation_rules:
  - path_regex: terraform/secrets.sops.yaml
    key_groups:
      - age:
          - age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
  - path_regex: secrets.sops.env
    key_groups:
      - age:
          - age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
